# This references a standard debian container from the
# Docker Hub https://registry.hub.docker.com/_/debian/
# Read more about containers on our dev center
# http://devcenter.wercker.com/docs/containers/index.html
box: kaixhin/cuda-torch
# You can also use services such as databases. Read more on our dev center:
# http://devcenter.wercker.com/docs/services/index.html
# services:
# - postgres
# http://devcenter.wercker.com/docs/services/postgresql.html

# - mongodb
# http://devcenter.wercker.com/docs/services/mongodb.html

# This is the build pipeline. Pipelines are the core of wercker
# Read more about pipelines on our dev center
# http://devcenter.wercker.com/docs/pipelines/index.html
build:
  # Steps make up the actions in your pipeline
  # Read more about steps on our dev center:
  # http://devcenter.wercker.com/docs/steps/index.html
  steps:
    - script:
      name: install
      code: |
        apt-get -yqq update
        apt-get install -yqq wget
        luarocks make
    - script:
      name: test and generate coverage
      code: |
        luarocks install luacov
        th -lluacov test.lua
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    - script:
      name: generate markdown
      code: |
        git clone https://github.com/vzhong/docroc.git
        cd docroc && luarocks make && cd -
        th docroc/docroc src docs --index README.md --config mkdocs.yml --github_src_dir http://github.com/vzhong/torchlib/blob/master/src/
deploy:
  steps:
    - script:
      name: install dependencies
      code: |
        apt-get -yqq update
        apt-get install -yqq python python-pip
        apt-get install -yqq git
        pip install mkdocs
    - script:
      name: build docs
      code: |
        mkdocs build --clean
        touch site/.nojekyll
    - lukevivier/gh-pages:
      token: $GH_TOKEN
      basedir: site
